	MODULE ADJUSTI
	USE COMMONS
	CONTAINS
	SUBROUTINE ADJUST
	
	IMPLICIT NONE

	INTEGER :: OATTEMPT, ONACCEPT
	DOUBLE PRECISION :: OMAXSTEP, FRAC
	CHARACTER (LEN=20) :: AFILE
	OATTEMPT = 0
	ONACCEPT = 0
	AFILE= 'ADJUST.OUT'
	OPEN(UNIT=40, FILE=TRIM(AFILE), STATUS='UNKNOWN')
	
	IF (ATTEMPT .EQ. 0 .OR. OATTEMPT .GE. ATTEMPT) THEN

	ONACCEPT = NACCEPT
	OATTEMPT = ATTEMPT

	ELSE

	FRAC = (DBLE(NACCEPT)-DBLE(ONACCEPT))/(DBLE(ATTEMPT)-DBLE(OATTEMPT))
	OMAXSTEP = MAXSTEP
	MAXSTEP = MAXSTEP*ABS(FRAC/0.5D0)

!-------------LIMIT THE CHANGE IN STEP SIZE--------------------

		IF (MAXSTEP/OMAXSTEP .GT. 1.5D0) MAXSTEP = OMAXSTEP*1.5D0
		IF (MAXSTEP/OMAXSTEP .LT. 0.5D0) MAXSTEP = OMAXSTEP*0.5D0
		IF (MAXSTEP .GT. RADIUS/2.D0) MAXSTEP = RADIUS/2.D0
		WRITE(40, 2005) MAXSTEP, OMAXSTEP, FRAC, ATTEMPT-OATTEMPT, NACCEPT-ONACCEPT       
	END IF

	2005 FORMAT ('Max translational stepsize set to:', f6.3, 'Old transla&
	&tional step size:', f6.3, /, 'Fraction accepted:', f4.2, 'Attempts:',&
	&i7, 'Succesful attempts:' i7) 
	
	CLOSE(UNIT=40)
	RETURN

	END SUBROUTINE
	END MODULE
