	MODULE FINALSTOREI
	USE COMMONS
	CONTAINS
	
	SUBROUTINE FINALSTORE
	IMPLICIT NONE

	INTEGER :: I
	CHARACTER (LEN=20) :: FILENAME

	FILENAME='mcfinalconfig.xyz'
	OPEN(UNIT=32, FILE=FILENAME, STATUS='NEW')
	WRITE(32,*) 'NMOL =', NMOL, 'ENERGY =', ENERGY
	DO I=1, NMOL 
		WRITE(32,*) COORDS(3*I-2), COORDS(3*I-1), COORDS(3*1)
	END DO

	END SUBROUTINE
	END MODULE


