	PROGRAM MC_NVT_DM
	USE COMMONS
	USE READINPUTI
	USE READCOORDSI
	USE TOTALENERGYI
	USE OLDPENERGYI
	USE CALCUNITVECI
	USE CALCENERGYI
	USE ADJUSTI
	USE MC_STEPI
	USE NEWPENERGYI
	USE SAMPLEI
	USE STOREI
	USE FINALSTOREI
	
	IMPLICIT NONE
	
	CHARACTER (LEN=10) :: FILENAME
	
	!READ INPUT DATA
	CALL READINPUT
	
	ALLOCATE(QUARTS(3,NMOL))
	ALLOCATE(COORDS(4,NMOL))
	CALL READCOORDS
	write(*,*) 'main prog', QUARTS
	
	!OPEN OUTPUT FILE
	FILENAME = 'OUTPUT'
	OPEN( UNIT =23, FILE = FILENAME, STATUS = 'UNKNOWN' ) 

	WRITE(23,*) 'MC_NVT_DM', NMOL
	
	!CALCULATE ENERGY OF ORIGINAL RANDOM SYSTEM
	CALL TOTALENERGY
	
	WRITE(23,*) 'TOTAL ENERGY OF INITIAL COFIGURATION:', ENERGY
	
	!BEGIN MC ALGORITHM

	DO II = 1, 2 !II=1=EQUILIBRATION, II=2=PRODUCTION

		IF (II==1) THEN 
			NCYCLE = NMCE
			IF (NCYCLE.NE.0) THEN
				WRITE(23,*) '------------START EQUILIBRATION------------'
			END IF
		ELSE
			NCYCLE = NMCP
			IF (NCYCLE.NE.0) THEN
				WRITE(23,*) '-------------START PRODUCTION------------'
			END IF
		END IF


		ATTEMPT = 0
		NACCEPT = 0    
		
		!INITIALISE SUBROUTINE TO OPTIMISE STEPSIZE
		CALL ADJUST

		DO ICYCLE = 1, NCYCLE

			DO IMOVE = 1, NDISP
				CALL MC_STEP !MC_STEP SUBROUTINE PERFORMS RANDOMDISPLACEMENT, CALCULATES ENERGY,  ACCEPTS AND REJECTS
			END DO

			IF (II==2) THEN
				IF (MOD(ICYCLE,NMCS)==0) THEN
					CALL SAMPLE !SAMPLES AVERAGE ENERGY AND PRESSURE
				END IF
			END IF

			IF (MOD(ICYCLE,NCYCLE/5)==0) THEN
				CALL STORE !STORES CONFIGURATION OF CANNONICAL ENSEMBLE
				CALL ADJUST !ADJUSTS STEPS SIZE TO IMPROVE EFFICIENCY
			END IF
			
			
			WRITE(23,*) 'STEP:', ICYCLE, 'ENERGY:', ENERGY
		END DO
		
		
		
		IF (NCYCLE .NE. 0) THEN
			IF (ATTEMPT .NE. 0) THEN
				WRITE(23,*) 'NUMBER OF ATTEMPTS TO DISPLACE PARTICLES:', ATTEMPT, 'SUCCESS:', NACCEPT, 100*FLOAT(NACCEPT)/FLOAT(ATTEMPT) 
			END IF
			
			IF (II==1) THEN
				CALL TOTALENERGY
				WRITE(23,*) 'TOTAL ENERGY AFTER EQUIBRILATION:', ENERGY
			ELSE IF (II==2) THEN
				CALL TOTALENERGY
				WRITE (23,*) 'TOTAL ENERGY AFTER PRODUCTION:', ENERGY
			END IF
		END IF
	END DO
	CALL FINALSTORE
	WRITE(*,*) 'THIS FAR'
	1001 FORMAT ( 'TOTAL ENERGY OF INITIAL COFIGURATION:', F12.5)
	1002 FORMAT ( 'NUMBER OF ATTEMPTS TO DISPLACE PARTICLES:', I10, / &
        & 'SUCCESS:', I10, '(', F5.2, '%)')
	1003 FORMAT ( 'TOTAL ENERGY AFTER EQUIBRILATION:', F12.5)
	1004 FORMAT ( 'TOTAL ENERGY AFTER PRODUCTION:', F12.5)

END PROGRAM MC_NVT_DM









