	MODULE MC_STEPI
	USE COMMONS
	USE OLDPENERGYI
	USE NEWPENERGYI
	CONTAINS
	
	SUBROUTINE MC_STEP
	
	IMPLICIT NONE

	INTEGER :: O, JB, P, IND
	DOUBLE PRECISION :: RANF
	DOUBLE PRECISION ::  DUMMY, KB, BETA
	DOUBLE PRECISION :: NEWCOORDS(3*NMOL), NEWQUARTS(4*NMOL)
	!O: RANDOMLY SELECTED PARTICLE
	!P: USED TO LOCATE THE X, Y AND Z VALUES OF PARTICLE O
	!OPENERGY: ENERGY OF PARTICLE IN OLD CONFIGURATION
	!NPENERGY: ENERGY OF PARTICLE IN NEW CONFIGURATION
	!NEWCOORDS: CONFIGURATION OF SYSTEM AFTER DISPLACEMENT
	!KB: BOLTZMAN CONSTANT
	!IND: INDICATOR FOR PENERGY SUBROUTINE LOOP TO USE COORDS OR NEWCORDS 
	
	ATTEMPT = ATTEMPT + 1
	O = 0
	JB = 1

	!-------------------------SELECT RANDOM PARTICLE-------------------------------
	O = INT(DBLE(NMOL)*RANF(DUMMY) + 1)
	IND = 1

	
	!-----------CALCULATE ENERGY OF THE PARTICLE IN THE OLD CONFIGURATION----------
	CALL OLDPENERGY(O, JB, IND)


	!--------------------------DISPLACE RANDOM PARTICLE----------------------------
	NEWCOORDS = COORDS
	NEWQUARTS = QUARTS
	IND = 2
	P = 3*O
	Q = 4*O
	!DISPLACE ALONG X-AXIS
	NEWCOORDS(P-2) = NEWCOORDS(P-2) + (MAXSTEP*RANF(DUMMY))
	!DISPLACE ALONG Y-AXIS
	NEWCOORDS(P-1) = NEWCOORDS(P-1) + (MAXSTEP*RANF(DUMMY))
	!DISPLACE ALONG Z-AXIS
	NEWCOORDS(P) = NEWCOORDS(P) + (MAXSTEP*RANF(DUMMY))
	!DISPLACE Q1
	NEWQUARTS(Q-3) = NEWQUARTS(Q-3) + (MAXROT*RANF(DUMMY))
	!DISPLACE Q2
	NEWQUARTS(Q-2) = NEWQUARTS(Q-2) + (MAXROT*RANF(DUMMY)
	!DISPLACE Q3
	NEWQUARTS(Q-1) = NEWQUARTS(Q-1) + (MAXROT*RANF(DUMMY)
	!DISPLACE Q4
	NEWQUARTS(Q) = NEWQUARTS(Q) + (MAXROT*RANF(DUMMY)
	!------------ENSURE THAT THE PARTICLE IS WITHIN THE SIMULATION BOX------------
	IF (NEWCOORDS(P-2) > RADIUS) NEWCOORDS(P-2) = NEWCOORDS(P-2) - L
	IF (NEWCOORDS(P-2) < (-RADIUS)) NEWCOORDS(P-2) = NEWCOORDS(P-2) + L
	IF (NEWCOORDS(P-1) > RADIUS) NEWCOORDS(P-1) = NEWCOORDS(P-1) - L
	IF (NEWCOORDS(P-1) < (-RADIUS)) NEWCOORDS(P-1) = NEWCOORDS(P-1) + L
	IF (NEWCOORDS(P) > RADIUS) NEWCOORDS(P) = NEWCOORDS(P) - L
	IF (NEWCOORDS(P) < (-RADIUS)) NEWCOORDS(P) = NEWCOORDS(P) + L 

	!----------CALCULATE ENERGY OF THE PARTILCE IN THE NEW CONFIGURATION----------
	CALL NEWPENERGY(NEWCOORDS, NEWQUARTS, O, JB, IND)


	!------------------ACCEPT OR REJECT NEW CONFIGURATION-------------------------
	KB = 1.0D0
	BETA = -1/(KB*TEMP)
	IF (NPENERGY < OPENERGY) THEN
		COORDS = NEWCOORDS
		NACCEPT = NACCEPT + 1
		ENERGY = ENERGY - OPENERGY + NPENERGY
	ELSE IF (RANF(DUMMY) < DEXP(-(NPENERGY-OPENERGY)/TEMP)) THEN
		COORDS = NEWCOORDS
		NACCEPT = NACCEPT + 1
		ENERGY = ENERGY - OPENERGY + NPENERGY
	END IF
	RETURN
	END SUBROUTINE
	END MODULE

!-------------------------------------------------------------------------------------------------------------------------------------------------------------

        DOUBLE PRECISION FUNCTION RANF(DUMMY)

        !FUNCTION TO GENERATE A UNIFORMLY RANDOM NUMBER BETWEEN 0 AND 1

        INTEGER, PARAMETER :: L = 1029, C = 221591, M = 1048576
        INTEGER ::          SEED
        DOUBLE PRECISION :: DUMMY
        SAVE             SEED
        DATA             SEED / 0 /

        SEED = MOD(SEED * L + C, M)
        RANF = DFLOAT(SEED) / DFLOAT(M)

        END FUNCTION RANF

