	MODULE READINPUTI
	USE COMMONS
	CONTAINS
	SUBROUTINE READINPUT
	IMPLICIT NONE

!-------------------------READ INPUT PARAMETERS-------------------------------------
	CHARACTER (LEN=10) :: FILENAME 
	DOUBLE PRECISION, PARAMETER :: PI = 4*ATAN(1.0)
	!READ INPUT PARAMETERS
	FILENAME = 'INPUT.DATA'
	OPEN(UNIT = 22, FILE = FILENAME, STATUS = 'OLD') 
	
	READ(22,1005) NMOL, RADIUS, TEMP, NMCE, NMCP, NMCS, NDISP, MAXSTEP, &
	&MAXROT

	1005 FORMAT(I10, /, F10.2, /, F10.2, / I10, /, I10, /, I10, /, I10, /,&
        & F10.2, /, F10.2)

	L = 2*RADIUS
	ALPHA = 5/L
	FSPACELIMIT = NINT(((ALPHA^2)*RADIUS*L)/PI)
	NMOL = NATOM
	END SUBROUTINE
	END MODULE

