	MODULE TOTALENERGYI
	USE COMMONS
	USE OLDPENERGYI
	CONTAINS
	
	SUBROUTINE TOTALENERGY
	IMPLICIT NONE
	!CALCULATE THE POTENTIAL OF ALL PARTICLE IN THE SYSTEM RELATIVE TO ONE ANOTHER

	INTEGER :: I, JB, O, IND
	
	ENERGY = 0.D0
	IND = 1
	DO I = 1, NMOL-1
		O = I
		JB = I +1
		CALL OLDPENERGY(O, JB, IND)
		ENERGY = ENERGY + OPENERGY
	END DO


	RETURN
	END SUBROUTINE
	END MODULE

